name: flutter_series
description: >
  Improved row and column widgets to include spacing and interleaved dividers.
version: 0.1.2
repository: https://github.com/danjoemybro/flutter_series

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: