name: flutter_series
description: >
  Improved row and column widgets to include spacing and interleaved dividers.
version: 0.0.2
homepage: "https://freshplay.co.uk/"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: